question_one = Question.find(10) # fever
question_two = Question.find(11)
question_three = Question.find(12)
question_four = Question.find(13)
question_five = Question.find(14)
question_six = Question.find(15)
question_seven = Question.find(16)
question_eight = Question.find(17)

Answer.create(option: "häufig", category: "fever", question: question_one)
Answer.create(option: "selten", category: "fever", question: question_one)
Answer.create(option: "manchmal", category: "limbs", question: question_two)
Answer.create(option: "häufig", category: "limbs", question: question_two)
Answer.create(option: "manchmal", category: "neck", question: question_three)
Answer.create(option: "häufig", category: "neck", question: question_three)
Answer.create(option: "häufig (trocken)", category: "cough", question: question_four)
Answer.create(option: "wenig", category: "cough", question: question_four)
Answer.create(option: "manchmal", category: "head", question: question_five)
Answer.create(option: "selten", category: "head", question: question_five)
Answer.create(option: "häufig", category: "head", question: question_five)
Answer.create(option: "manchmal", category: "fatigue", question: question_six)
Answer.create(option: "häufig", category: "fatigue", question: question_six)
Answer.create(option: "häufig", category: "sneeze", question: question_seven)
Answer.create(option: "selten", category: "sniff", question: question_eight)
Answer.create(option: "häufig", category: "sniff", question: question_eight)
Answer.create(option: "manchmal", category: "sniff", question: question_eight)

